name: Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up shell environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install
        run: bash scripts/install.sh

      - name: Run configure script
        run: |
          adbm configure pat=$AZURE_PAT
          adbm configure project=$AZURE_PROJECT
          adbm configure organization=$AZURE_ORG
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
          AZURE_ORG: ${{ secrets.AZURE_ORGANIZATION }}
          AZURE_PROJECT: ${{ secrets.AZURE_PROJECT }}

      - name: Run help command
        run: adbm help

      - name: Run version command
        run: adbm version

      - name: ShellCheck Lint
        run: |
          shellcheck bin/*
